name: cracktech_assessment
description: Assessment for Crack Tech Ltd.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  lottie: ^2.5.0
  dio: ^5.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  logger: ^1.1.0
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/


